/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora_Financ;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class Calc_Amortizacao extends javax.swing.JFrame {

    /**
     * Creates new form Calc_Amortizacao
     */
    public Calc_Amortizacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_vrFinanc = new javax.swing.JTextField();
        txt_TaxaFinanc = new javax.swing.JTextField();
        txt_TempoFinanc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtn_Sac = new javax.swing.JButton();
        jBtn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Financiamento");

        jLabel2.setText("Taxa");

        jLabel3.setText("Tempo");

        jBtn_Sac.setText("SAC");
        jBtn_Sac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SacActionPerformed(evt);
            }
        });

        jBtn_Limpar.setText("Limpar");
        jBtn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_vrFinanc, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txt_TaxaFinanc)
                    .addComponent(txt_TempoFinanc))
                .addGap(269, 269, 269))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_Sac)
                    .addComponent(jBtn_Limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_vrFinanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TaxaFinanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TempoFinanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jBtn_Sac)
                        .addGap(62, 62, 62)
                        .addComponent(jBtn_Limpar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Calc_Amortiz CalcSacObj;

    DecimalFormat df = new DecimalFormat("0.##");

    int lin, ncol, i, j;

    public void CalculoSac() {

        String[] cols = {"n.Parc", "SaldoIni", "Juros", "Amort", "Vr.Parc", "SaldoFim"};

//                col = Cabecalho[0].length;
        lin = CalcSacObj.getTempo();
        int ncol = cols.length;

//        double[][] calculo = new double[lin][ncol];
        String[][] calculo = new String[lin][ncol];
        //String[][] Cabecalho = new String[lin][col];

        for (i = 0; i < lin; i++) {

            CalcSacObj.CalcSac();

            for (j = 0; j < ncol; j++) {
                switch (j) {
                    case 0:
                        calculo[i][j] = Integer.toString(CalcSacObj.getNumparc());
                        break;

                    case 1:
                        calculo[i][j] = df.format(CalcSacObj.getVrpres());
                        break;

                    case 2:
                        //calculo[i][j] = Double.toString(CalcSacObj.getJuros());
                        calculo[i][j] = df.format(CalcSacObj.getJuros());
                        break;

                    case 3:
                        // calculo[i][j] = Double.toString(CalcSacObj.getAmortiz());
                        calculo[i][j] = df.format(CalcSacObj.getAmortiz());
                        break;

                    case 4:
                        //    calculo[i][j] = Double.toString(CalcSacObj.getVrparc())
                        calculo[i][j] = df.format(CalcSacObj.getVrparc());
                        break;

                    case 5:
                        //    calculo[i][j] = Double.toString(CalcSacObj.getSaldofim());
                        calculo[i][j] = df.format(CalcSacObj.getSaldofim());
                        break;

                    default:
                        System.out.print("Coluna não encontrada!");
                        break;
                }

            }
            CalcSacObj.setVrpres(CalcSacObj.getSaldofim());
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setDataVector(calculo, cols);

    }


    private void jBtn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_LimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_LimparActionPerformed

    private void jBtn_SacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SacActionPerformed
        // TODO add your handling code here:

        if (txt_vrFinanc.getText().isEmpty() || txt_TaxaFinanc.getText().isEmpty()
                || txt_TempoFinanc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos não podem estar vazios");
        } else {

            CalcSacObj = new Calc_Amortiz();
//        CalculoObj.vrpres = Double.parseDouble(txt_vp.getText());
            CalcSacObj.setVrpres(Double.parseDouble((txt_vrFinanc.getText()).replaceAll(",", ".")));
            CalcSacObj.setTaxa(Double.parseDouble((txt_TaxaFinanc.getText()).replaceAll(",", ".")));
            CalcSacObj.setTempo(Integer.parseInt((txt_TempoFinanc.getText()).replaceAll(",", ".")));
            CalcSacObj.setAmortiz(Double.parseDouble((txt_vrFinanc.getText()).replaceAll(",", ".")) / Double.parseDouble((txt_TempoFinanc.getText()).replaceAll(",", ".")));
            //           CalcSacObj.setAmortiz(CalcSacObj.getVrparc()/Double.parseDouble(CalcSacObj.getTempo()));

            CalculoSac();

        }
    }//GEN-LAST:event_jBtn_SacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc_Amortizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc_Amortizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc_Amortizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc_Amortizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc_Amortizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Limpar;
    private javax.swing.JButton jBtn_Sac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_TaxaFinanc;
    private javax.swing.JTextField txt_TempoFinanc;
    private javax.swing.JTextField txt_vrFinanc;
    // End of variables declaration//GEN-END:variables
}
